//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMO_AZS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class СМО_АЗСEntities : DbContext
    {
        public СМО_АЗСEntities()
            : base("name=СМО_АЗСEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Исходные_данные> Исходные_данные { get; set; }
        public virtual DbSet<Очередь_с_неограниченным_ожиданием> Очередь_с_неограниченным_ожиданием { get; set; }
        public virtual DbSet<Очередь_с_ограничением_длины> Очередь_с_ограничением_длины { get; set; }
        public virtual DbSet<Очередь_с_отказом> Очередь_с_отказом { get; set; }
        public virtual DbSet<Эксперимент> Эксперимент { get; set; }
    }
}
