//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMO_AZS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Исходные_данные
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Исходные_данные()
        {
            this.Очередь_с_отказом = new HashSet<Очередь_с_отказом>();
            this.Очередь_с_ограничением_длины = new HashSet<Очередь_с_ограничением_длины>();
            this.Очередь_с_неограниченным_ожиданием = new HashSet<Очередь_с_неограниченным_ожиданием>();
        }
    
        public int Id { get; set; }
        public int Эксперимент_Id { get; set; }
        public int Число_каналов { get; set; }
        public double Интенсивность_входного_потока__число_клиентов_ { get; set; }
        public double Среднее_время_обслуживания_одной_заявки_в_минутах { get; set; }
        public double Интенсивность_потока_обслуживания { get; set; }
        public double Интенсивность_нагрузки { get; set; }
        public Nullable<int> Продолжительность_рабочего_дня_в_часах { get; set; }
        public Nullable<double> Требуемая_вероятность_обслуживания { get; set; }
        public Nullable<int> Длина_очереди { get; set; }
    
        public virtual Эксперимент Эксперимент { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Очередь_с_отказом> Очередь_с_отказом { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Очередь_с_ограничением_длины> Очередь_с_ограничением_длины { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Очередь_с_неограниченным_ожиданием> Очередь_с_неограниченным_ожиданием { get; set; }
    }
}
