//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMO_AZS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Эксперимент
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Эксперимент()
        {
            this.Исходные_данные = new HashSet<Исходные_данные>();
        }
    
        public int Id { get; set; }
        public System.DateTime Дата_эксперимента { get; set; }
        public string Постановка_задачи { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Исходные_данные> Исходные_данные { get; set; }
    }
}
